import {
  faBellConcierge,
  faCircleXmark,
  faEarthEurope,
  faEnvelope,
  faHouseChimney,
  faInfoCircle,
  faUser,
  faCog,
  faCaretDown,
  faCaretRight,
  faCaretLeft,
  faCaretUp,
  faCode,
  faSearch,
  faMugHot,
} from "@fortawesome/free-solid-svg-icons";
import {
  faSquareFacebook,
  faSquareSnapchat,
  faXTwitter,
  faInstagram,
  faLinkedin,
  faGithub,
  faPinterest,
  faYoutube,
  faGoogle,
  faTumblr,
  faFlickr,
  faVimeo,
  faMedium,
  faWhatsapp,
  faTelegram,
  faSlack,
  faDiscord,
  faReddit,
  faTiktok,
  faSpotify,
  faSoundcloud,
  faBandcamp,
  faLastfm,
  faTwitch,
  faSteam,
  faXbox,
  faPlaystation,
  faItchIo,
  faEtsy,
  faPatreon,
  faPaypal,
  faAmazon,
  faEbay,
} from "@fortawesome/free-brands-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-common-types";

export const iconRegistry: {
  solid: Record<string, IconDefinition>;
  brands: Record<string, IconDefinition>;
} = {
  solid: {
    bell: faBellConcierge,
    close: faCircleXmark,
    code: faCode,
    coffee: faMugHot,
    home: faHouseChimney,
    user: faUser,
    search: faSearch,
    settings: faCog,
    earth: faEarthEurope,
    envelope: faEnvelope,
    info: faInfoCircle,

    down: faCaretDown,
    right: faCaretRight,
    left: faCaretLeft,
    up: faCaretUp,
  },

  brands: {
    facebook: faSquareFacebook,
    x: faXTwitter,
    snapchat: faSquareSnapchat,
    instagram: faInstagram,
    linkedin: faLinkedin,
    github: faGithub,
    pinterest: faPinterest,
    youtube: faYoutube,
    google: faGoogle,
    tumblr: faTumblr,
    flickr: faFlickr,
    vimeo: faVimeo,
    medium: faMedium,
    whatsapp: faWhatsapp,
    telegram: faTelegram,
    slack: faSlack,
    discord: faDiscord,
    reddit: faReddit,
    tiktok: faTiktok,
    spotify: faSpotify,
    soundcloud: faSoundcloud,
    bandcamp: faBandcamp,
    lastfm: faLastfm,
    twitch: faTwitch,
    steam: faSteam,
    xbox: faXbox,
    playstation: faPlaystation,
    itchio: faItchIo,
    etsy: faEtsy,
    patreon: faPatreon,
    paypal: faPaypal,
    amazon: faAmazon,
    ebay: faEbay,
  },
} as const;

export type IconPack = keyof typeof iconRegistry;
export type IconName<P extends IconPack = IconPack> =
  keyof (typeof iconRegistry)[P];
