version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "*storybook"
    target-branch: "release"
    assignees:
      - "nick8green"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release"
    assignees:
      - "nick8green"
