name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels:
  - enhancement
  - triage
projects:
  - nick8green/9
assignees:
  - nick8green
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements!
  - type: textarea
    id: feature
    attributes:
      label: Describe the solution/feature you'd like
      description: A clear and concise description of what you want to happen. Please include screenshots if available.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
