import type { IconDefinition } from '@fortawesome/fontawesome-common-types';
import {
  faAmazon,
  faBandcamp,
  faDiscord,
  faEbay,
  faEtsy,
  faFlickr,
  faGithub,
  faGoogle,
  faInstagram,
  faItchIo,
  faLastfm,
  faLinkedin,
  faMedium,
  faPatreon,
  faPaypal,
  faPinterest,
  faPlaystation,
  faReddit,
  faSlack,
  faSoundcloud,
  faSpotify,
  faSquareFacebook,
  faSquareSnapchat,
  faSteam,
  faTelegram,
  faTiktok,
  faTumblr,
  faTwitch,
  faVimeo,
  faWhatsapp,
  faXbox,
  faXTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';
import {
  faBellConcierge,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCircleXmark,
  faCode,
  faCog,
  faEarthEurope,
  faEnvelope,
  faHouseChimney,
  faInfoCircle,
  faMugHot,
  faSearch,
  faUser,
} from '@fortawesome/free-solid-svg-icons';

export const iconRegistry: {
  solid: Record<string, IconDefinition>;
  brands: Record<string, IconDefinition>;
} = {
  solid: {
    bell: faBellConcierge,
    close: faCircleXmark,
    code: faCode,
    coffee: faMugHot,
    home: faHouseChimney,
    user: faUser,
    search: faSearch,
    settings: faCog,
    earth: faEarthEurope,
    envelope: faEnvelope,
    info: faInfoCircle,

    down: faCaretDown,
    right: faCaretRight,
    left: faCaretLeft,
    up: faCaretUp,
  },

  brands: {
    facebook: faSquareFacebook,
    x: faXTwitter,
    snapchat: faSquareSnapchat,
    instagram: faInstagram,
    linkedin: faLinkedin,
    github: faGithub,
    pinterest: faPinterest,
    youtube: faYoutube,
    google: faGoogle,
    tumblr: faTumblr,
    flickr: faFlickr,
    vimeo: faVimeo,
    medium: faMedium,
    whatsapp: faWhatsapp,
    telegram: faTelegram,
    slack: faSlack,
    discord: faDiscord,
    reddit: faReddit,
    tiktok: faTiktok,
    spotify: faSpotify,
    soundcloud: faSoundcloud,
    bandcamp: faBandcamp,
    lastfm: faLastfm,
    twitch: faTwitch,
    steam: faSteam,
    xbox: faXbox,
    playstation: faPlaystation,
    itchio: faItchIo,
    etsy: faEtsy,
    patreon: faPatreon,
    paypal: faPaypal,
    amazon: faAmazon,
    ebay: faEbay,
  },
} as const;

export type IconPack = keyof typeof iconRegistry;
export type IconName<P extends IconPack = IconPack> = keyof (typeof iconRegistry)[P];
