name: build checks for application

on:
  workflow_call:
  workflow_dispatch:

jobs:
  # run unit tests
  test:
    name: 🧪 unit tests
    uses: nick8green/workflows/.github/workflows/node-unit-test.yml@node-setup
    secrets:
      token: ${{ secrets.GH_PAT }}

  # build package
  build:
    name: 🏗️ build package
    uses: nick8green/workflows/.github/workflows/node-build.yml@node-setup
    secrets:
      token: ${{ secrets.GH_PAT }}

  # build storybook
  storybook:
    name: 📚 build storybook
    uses: ./.github/workflows/storybook-build-and-deploy.yml
    with:
      deploy: false

  # lint code
  linting:
    name: ✏️ lint code
    uses: nick8green/workflows/.github/workflows/node-inspect.yml@node-setup
    secrets:
      token: ${{ secrets.GH_PAT }}
